global using Filemanager.Application.DTOS;
global using Microsoft.AspNetCore.Http;
global using AutoMapper;
global using Filemanager.Application.Constract;
global using Filemanager.Application.Tools;
global using FileManager.Domain.Entities;
global using FileManager.Infrastructure.Persistence;
global using Microsoft.EntityFrameworkCore;
global using System.Globalization;
